FROM csprock/vscodebase:0.0

RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y \
    python3.9 \
    python3.9-distutils \
    && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3.9 get-pip.py \
    && rm get-pip.py \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add VS Code extensions
COPY ./scripts/extension_list /tmp/extension_list
COPY ./scripts/install_extensions.sh /config/custom-cont-init.d/install_extensions.sh


COPY ./scripts/install-r-packages.sh /tmp/install-r-packages.sh
RUN sh /tmp/install-r-packages.sh && rm /tmp/install-r-packages.sh
